export enum EntityType {
  SOURCEIP = 'SOURCEIP',
  DSTIP = 'DSTIP',
  SOURCEDOMAIN = 'SOURCEDOMAIN',
  DSTDOMAIN = 'DSTDOMAIN',
  SOURCEHOST = 'SOURCEHOST',
  DSTHOST = 'DSTHOST',
  SOURCESYSTEMLOCATIONCOUNTRY = 'SOURCESYSTEMLOCATIONCOUNTRY',
  SOURCESYSTEMLOCATIONCITY = 'SOURCESYSTEMLOCATIONCITY',
  SOURCESYSTEMLOCATIONSTATE = 'SOURCESYSTEMLOCATIONSTATE',
  SOURCESYSTEMLOCATIONLAT = 'SOURCESYSTEMLOCATIONLAT',
  SOURCESYSTEMLOCATIONLON = 'SOURCESYSTEMLOCATIONLON',
  DSTLOCATION = 'DSTLOCATION',
  SOURCEUSER = 'SOURCEUSER',
  DSTUSER = 'DSTUSER',
  SOURCEUSERDOMAIN = 'SOURCEUSERDOMAIN',
  DSTUSERDOMAIN = 'DSTUSERDOMAIN',
  SOURCEUSERNAME = 'SOURCEUSERNAME',
  DSTUSERNAME = 'DSTUSERNAME',
  SOURCEURL = 'SOURCEURL',
  DSTURL = 'DSTURL',
  SOURCEMAC = 'SOURCEMAC',
  DSTMAC = 'DSTMAC',
  SOURCEEMAIL = 'SOURCEEMAIL',
  DSTEMAIL = 'DSTEMAIL',
  HASH = 'HASH',
}

export enum EntitySuperTypes {
  DOMAIN = 'DOMAIN',
  URL = 'URL',
  IP = 'IP',
  MAC = 'MAC',
  USER = 'USER',
  LOCATION = 'LOCATION',
  EMAIL = 'EMAIL',
  HASH = 'HASH',
  HOSTNAME = 'HOSTNAME',
  OTHER = 'OTHER',
}

export enum EntityFamily {
  SYSTEM = 'SYSTEM',
  USER = 'USER',
  OTHER = 'OTHER',
}

export enum EntityDirection {
  NONE = 'NONE',
  SOURCE = 'SOURCE',
  DESTINATION = 'DESTINATION',
}

export enum AlertFiltersAlertExtraDataSearchType {
  OR = 'OR',
  AND = 'AND',
}

export enum AlertFiltersOrderBy {
  IMPACT = 'IMPACT',
  ALERTPRIORITY = 'ALERTPRIORITY',
}

export enum AlertFiltersGroupBy {
  ENTITY = 'ENTITY',
  ALERTTYPE = 'ALERTTYPE',
  NOGROUP = 'NOGROUP',
}

export enum AlertCommentSecOpsCommentType {
  ALERT = 'ALERT',
  REPLY = 'REPLY',
}

export enum AlertCommentSecOpsBulkUpdateCommentType {
  ALERT = 'ALERT',
  REPLY = 'REPLY',
}

export enum AlertCommentSecOpsBulkCommentType {
  ALERT = 'ALERT',
  REPLY = 'REPLY',
}
